import Link from 'next/link'
import styles from "../styles/privacy_Notice.module.css";

export default function Button() {
  return (
    <div class={styles.aboutUs}>
      <title>Privacy Notice</title>
      <div class={styles.salOf_spades}>
                    <div class={styles.navBar}>
                        <div>
                            <img src="Logo_Small Header 1.png"></img>
                            <Link href="/"> 
                            <h1 class={styles.h1}> SPADES </h1>
                             </Link>
                        </div>
                        <div class={styles.buttonContainer}>
                            <Link href="/about_Us"> 
                            <a class={styles.button}> ABOUT US </a>
                             </Link>
                             <Link href="barbers"> 
                            <a class={styles.button}> BARBERS </a>
                             </Link>
                             <Link href="/haircuts"> 
                            <a class={styles.button}> HAIRCUTS </a>
                             </Link>
                             <Link href="/reservation"> 
                            <a class={styles.button}> RESERVATION </a>
                             </Link>
                             <Link href="/privacy_Notice"> 
                            <a class={styles.button}> PRIVACY NOTICE </a>
                             </Link>                       
                        </div>
                    </div>
                    <div class={styles.privacyNotice}>
                        <h1> SPADES PRIVACY NOTICE </h1>
                    </div>
                    <div class={styles.content}>
                      <p> 1. Introduction
                      <br></br><br></br>
Welcome to Salon of Spades.
<br></br><br></br>
Spades (“us”, “we”, or “our”) operates Spades.com (hereinafter referred to as “Service”).
<br></br><br></br>
Our Privacy Policy governs your visit to Spades.com, and explains how we collect, safeguard and disclose information that results from your use of our Service.
<br></br><br></br>
We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
<br></br><br></br>
Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“agreement”).
<br></br><br></br>
2. Definitions
<br></br><br></br>
SERVICE means the SalonOfSpades.com website operated by Spades.
<br></br><br></br>
PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
<br></br><br></br>
USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).
<br></br><br></br>
COOKIES are small files stored on your device (computer or mobile device).
<br></br><br></br>
DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.
<br></br><br></br>
DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
<br></br><br></br>
DATA SUBJECT is any living individual who is the subject of Personal Data.
<br></br><br></br>
THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
<br></br><br></br>
3. Information Collection and Use
<br></br><br></br>
We collect several different types of information for various purposes to provide and improve our Service to you.
<br></br><br></br>
4. Types of Data Collected
<br></br><br></br>
Personal Data
<br></br><br></br>
While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:
<br></br><br></br>
0.1. FIRST NAME AND LAST NAME
<br></br><br></br>
0.2. AGE
<br></br><br></br>
0.3. GENDER
<br></br><br></br>
0.4. Phone number
<br></br><br></br>
0.5. Cookies and Usage Data
<br></br><br></br>
We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.
<br></br><br></br>
Usage Data
<br></br><br></br>
We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (“Usage Data”).
<br></br><br></br>
This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
<br></br><br></br>
When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.
<br></br><br></br>
Tracking Cookies Data
<br></br><br></br>
We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
<br></br><br></br>
Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.
<br></br><br></br>
You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
<br></br><br></br>
Examples of Cookies we use:
<br></br><br></br>
0.1. Session Cookies: We use Session Cookies to operate our Service.
<br></br><br></br>
0.2. Preference Cookies: We use Preference Cookies to remember your preferences and various settings.
<br></br><br></br>
0.3. Security Cookies: We use Security Cookies for security purposes.
<br></br><br></br>
0.4. Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.
<br></br><br></br>
Other Data
<br></br><br></br>
While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, NDA agreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location and other data.
<br></br><br></br>
5. Use of Data
<br></br><br></br>
Spades uses the collected data for various purposes:
<br></br><br></br>
0.1. to provide and maintain our Service;
<br></br><br></br>
0.2. to notify you about changes to our Service;
<br></br><br></br>
0.3. to allow you to participate in interactive features of our Service when you choose to do so;
<br></br><br></br>
0.4. to provide customer support;
<br></br><br></br>
0.5. to gather analysis or valuable information so that we can improve our Service;
<br></br><br></br>
0.6. to monitor the usage of our Service;
<br></br><br></br>
0.7. to detect, prevent and address technical issues;
<br></br><br></br>
0.8. to fulfil any other purpose for which you provide it;
<br></br><br></br>
0.9. to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;
<br></br><br></br>
0.10. to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;
<br></br><br></br>
0.11. to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;
<br></br><br></br>
0.12. in any other way we may describe when you provide the information;
<br></br><br></br>
0.13. for any other purpose with your consent.
<br></br><br></br>
6. Retention of Data
<br></br><br></br>
We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
<br></br><br></br>
We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
<br></br><br></br>
7. Transfer of Data
<br></br><br></br>
Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
<br></br><br></br>
If you are located outside Philippines and choose to provide information to us, please note that we transfer the data, including Personal Data, to Philippines and process it there.
<br></br><br></br>
Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
<br></br><br></br>
Spades will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.
<br></br><br></br>
8. Disclosure of Data
<br></br><br></br>
We may disclose personal information that we collect, or you provide:
<br></br><br></br>
0.1. Disclosure for Law Enforcement.
<br></br><br></br>
Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.
<br></br><br></br>
0.2. Business Transaction.
<br></br><br></br>
If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.
<br></br><br></br>
0.3. Other cases. We may disclose your information also:
<br></br><br></br>
0.3.1. to our subsidiaries and affiliates;
<br></br><br></br>
0.3.2. to contractors, service providers, and other third parties we use to support our business;
<br></br><br></br>
0.3.3. to fulfill the purpose for which you provide it;
<br></br><br></br>
0.3.4. for the purpose of including your company’s logo on our website;
<br></br><br></br>
0.3.5. for any other purpose disclosed by us when you provide the information;
<br></br><br></br>
0.3.6. with your consent in any other cases;
<br></br><br></br>
0.3.7. if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.
<br></br><br></br>
9. Security of Data
<br></br><br></br>
The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
<br></br><br></br>
10. Your Data Protection Rights Under General Data Protection Regulation (GDPR)
<br></br><br></br>
If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR.
<br></br><br></br>
We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
<br></br><br></br>
If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at website@gmail.com.
<br></br><br></br>
In certain circumstances, you have the following data protection rights:
<br></br><br></br>
0.1. the right to access, update or to delete the information we have on you;
<br></br><br></br>
0.2. the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;
<br></br><br></br>
0.3. the right to object. You have the right to object to our processing of your Personal Data;
<br></br><br></br>
0.4. the right of restriction. You have the right to request that we restrict the processing of your personal information;
<br></br><br></br>
0.5. the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;
<br></br><br></br>
0.6. the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;
<br></br><br></br>
Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.
<br></br><br></br>
You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
<br></br><br></br>
11. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)
<br></br><br></br>
CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy.
<br></br><br></br>
According to CalOPPA we agree to the following:
<br></br><br></br>
0.1. users can visit our site anonymously;
<br></br><br></br>
0.2. our Privacy Policy link includes the word “Privacy”, and can easily be found on the home page of our website;
<br></br><br></br>
0.3. users will be notified of any privacy policy changes on our Privacy Policy Page;
<br></br><br></br>
0.4. users are able to change their personal information by emailing us at website@gmail.com.
<br></br><br></br>
Our Policy on “Do Not Track” Signals:
<br></br><br></br>
We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
<br></br><br></br>
You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
<br></br><br></br>
12. Service Providers
<br></br><br></br>
We may employ third party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.
<br></br><br></br>
These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
<br></br><br></br>
13. Analytics
<br></br><br></br>
We may use third-party Service Providers to monitor and analyze the use of our Service.
<br></br><br></br>
14. CI/CD tools
<br></br><br></br>
We may use third-party Service Providers to automate the development process of our Service.
<br></br><br></br>
15. Behavioral Remarketing
<br></br><br></br>
We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.
<br></br><br></br>
16. Changes to This Privacy Policy
<br></br><br></br>
We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
<br></br><br></br>
We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.
<br></br><br></br>
You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
<br></br><br></br>
17. Contact Us
<br></br><br></br>
If you have any questions about this Privacy Policy, please contact us by email: spades@CARDS.com</p>
                    </div>
                </div>
    </div>
  );
}